font:
  normal:
    family: "NotoSansMono Nerd Font"
    style: Light
  bold:
    family: "NotoSansMono Nerd Font"
    style: Medium
  size: 16
  offset:
    y: 0
    x: 0
background_opacity: 1
window:
  dimensions:
    columns: 400
    lines: 100
  padding:
    x: 0
    y: 0
cursor:
  style: Block
  unfocusedd_hollow: true
draw_bold_text_with_bright_colors: false
schemes:
  monokai_pro: &monokai_pro
    # Default colors
    primary:
      background: "0x2D2A2E"
      foreground: "0xFCFCFA"

    # Normal colors
    normal:
      black: "0x403E41"
      red: "0xFF6188"
      green: "0xA9DC76"
      yellow: "0xFFD866"
      blue: "0xFC9867"
      magenta: "0xAB9DF2"
      cyan: "0x78DCE8"
      white: "0xFCFCFA"

    # Bright colors
    bright:
      black: "0x727072"
      red: "0xFF6188"
      green: "0xA9DC76"
      yellow: "0xFFD866"
      blue: "0xFC9867"
      magenta: "0xAB9DF2"
      cyan: "0x78DCE8"
      white: "0xFCFCFA"
  oceanic_next: &oceanic_next
    # Default colors
    primary:
      background: '0x1b2b34'
      foreground: '0xd8dee9'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x1b2b34'
      cursor: '0xffffff'

    # Normal colors
    normal:
      black:   '0x343d46'
      red:     '0xEC5f67'
      green:   '0x99C794'
      yellow:  '0xFAC863'
      blue:    '0x6699cc'
      magenta: '0xc594c5'
      cyan:    '0x5fb3b3'
      white:   '0xd8dee9'

    # Bright colors
    bright:
      black:   '0x343d46'
      red:     '0xEC5f67'
      green:   '0x99C794'
      yellow:  '0xFAC863'
      blue:    '0x6699cc'
      magenta: '0xc594c5'
      cyan:    '0x5fb3b3'
      white:   '0xd8dee9'
  one_dark: &one_dark
    # Default colors
    primary:
      background: '#282c34'
      foreground: '#abb2bf'

    # Normal colors
    normal:
      # NOTE: Use '#131613' for the `black` color if you'd like to see
      # black text on the background.
      black:   '#282c34'
      red:     '#e06c75'
      green:   '#98c379'
      yellow:  '#d19a66'
      blue:    '#61afef'
      magenta: '#c678dd'
      cyan:    '#56b6c2'
      white:   '#abb2bf'

    # Bright colors
    bright:
      black:   '#5c6370'
      red:     '#e06c75'
      green:   '#98c379'
      yellow:  '#d19a66'
      blue:    '#61afef'
      magenta: '#c678dd'
      cyan:    '#56b6c2'
      white:   '#ffffff'
  base16_gruvbox_dark_soft: &base16_gruvbox_dark_soft
    # Default colors
    primary:
      background: '0x32302f'
      foreground: '0xd5c4a1'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x32302f'
      cursor: '0xd5c4a1'
    # Normal colors
    normal:
      black:   '0x32302f'
      red:     '0xfb4934'
      green:   '0xb8bb26'
      yellow:  '0xfabd2f'
      blue:    '0x83a598'
      magenta: '0xd3869b'
      cyan:    '0x8ec07c'
      white:   '0xd5c4a1'
    # Bright colors
    bright:
      black:   '0x665c54'
      red:     '0xfe8019'
      green:   '0x3c3836'
      yellow:  '0x504945'
      blue:    '0xbdae93'
      magenta: '0xebdbb2'
      cyan:    '0xd65d0e'
      white:   '0xfbf1c7'
  gruvbox_material_dark_medium: &gruvbox_material_dark_medium
    primary:
      background: '0x282828'
      foreground: '0xdfbf8e'

    normal:
      black:   '0x665c54'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xe78a4e'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xdfbf8e'

    bright:
      black:   '0x928374'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xe3a84e'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xdfbf8e'
colors: *gruvbox_material_dark_medium
