font:
  normal:
    family: Cica
    style: Regular
  bold:
    family: Cica
    style: Bold
  italic:
    family: Cica
    style: Oblique
  bold_italic:
    family: Cica
    style: BoldOblique
  size: 16
  offset:
    y: 0
    x: 0
background_opacity: 1
window:
  dimensions:
    columns: 400
    lines: 100
  padding:
    x: 0
    y: 0
cursor:
  style: Block
  unfocusedd_hollow: true
draw_bold_text_with_bright_colors: false
schemes:
  solarized_light: &solarized_light
    primary:
      background: '#fdf6e3' # base3
      foreground: '#657b83' # base00

    # Cursor colors
    cursor:
      text:   '#fdf6e3' # base3
      cursor: '#657b83' # base00

    # Normal colors
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    # Bright colors
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3
  solarized_dark: &solarized_dark
    # Default colors
    primary:
      background: '0x002b36' # base03
      foreground: '0x839496' # base0

    # Cursor colors
    cursor:
      text:   '0x002b36' # base03
      cursor: '0x839496' # base0

    # Normal colors
    normal:
      black:   '0x073642' # base02
      red:     '0xdc322f' # red
      green:   '0x859900' # green
      yellow:  '0xb58900' # yellow
      blue:    '0x268bd2' # blue
      magenta: '0xd33682' # magenta
      cyan:    '0x2aa198' # cyan
      white:   '0xeee8d5' # base2

    # Bright colors
    bright:
      black:   '0x002b36' # base03
      red:     '0xcb4b16' # orange
      green:   '0x586e75' # base01
      yellow:  '0x657b83' # base00
      blue:    '0x839496' # base0
      magenta: '0x6c71c4' # violet
      cyan:    '0x93a1a1' # base1
      white:   '0xfdf6e3' # base3
  monokai_pro: &monokai_pro
    # Default colors
    primary:
      background: "0x2D2A2E"
      foreground: "0xFCFCFA"

    # Normal colors
    normal:
      black: "0x403E41"
      red: "0xFF6188"
      green: "0xA9DC76"
      yellow: "0xFFD866"
      blue: "0xFC9867"
      magenta: "0xAB9DF2"
      cyan: "0x78DCE8"
      white: "0xFCFCFA"

    # Bright colors
    bright:
      black: "0x727072"
      red: "0xFF6188"
      green: "0xA9DC76"
      yellow: "0xFFD866"
      blue: "0xFC9867"
      magenta: "0xAB9DF2"
      cyan: "0x78DCE8"
      white: "0xFCFCFA"
  oceanic_next: &oceanic_next
    # Default colors
    primary:
      background: '0x1b2b34'
      foreground: '0xd8dee9'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x1b2b34'
      cursor: '0xffffff'

    # Normal colors
    normal:
      black:   '0x343d46'
      red:     '0xEC5f67'
      green:   '0x99C794'
      yellow:  '0xFAC863'
      blue:    '0x6699cc'
      magenta: '0xc594c5'
      cyan:    '0x5fb3b3'
      white:   '0xd8dee9'

    # Bright colors
    bright:
      black:   '0x343d46'
      red:     '0xEC5f67'
      green:   '0x99C794'
      yellow:  '0xFAC863'
      blue:    '0x6699cc'
      magenta: '0xc594c5'
      cyan:    '0x5fb3b3'
      white:   '0xd8dee9'
  base16_gruvbox_dark_pale: &base16_gruvbox_dark_pale
    # Default colors
    primary:
      background: '0x262626'
      foreground: '0xdab997'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x262626'
      cursor: '0xdab997'

    # Normal colors
    normal:
      black:   '0x262626'
      red:     '0xd75f5f'
      green:   '0xafaf00'
      yellow:  '0xffaf00'
      blue:    '0x83adad'
      magenta: '0xd485ad'
      cyan:    '0x85ad85'
      white:   '0xdab997'

    # Bright colors
    bright:
      black:   '0x8a8a8a'
      red:     '0xff8700'
      green:   '0x3a3a3a'
      yellow:  '0x4e4e4e'
      blue:    '0x949494'
      magenta: '0xd5c4a1'
      cyan:    '0xd65d0e'
      white:   '0xebdbb2'
  one_dark: &one_dark
    # Default colors
    primary:
      background: '#282c34'
      foreground: '#abb2bf'

    # Normal colors
    normal:
      # NOTE: Use '#131613' for the `black` color if you'd like to see
      # black text on the background.
      black:   '#282c34'
      red:     '#e06c75'
      green:   '#98c379'
      yellow:  '#d19a66'
      blue:    '#61afef'
      magenta: '#c678dd'
      cyan:    '#56b6c2'
      white:   '#abb2bf'

    # Bright colors
    bright:
      black:   '#5c6370'
      red:     '#e06c75'
      green:   '#98c379'
      yellow:  '#d19a66'
      blue:    '#61afef'
      magenta: '#c678dd'
      cyan:    '#56b6c2'
      white:   '#ffffff'
colors: *one_dark
