font:
  normal:
    family: Menlo for Powerline
  bold:
    family: Menlo for Powerline
  italic:
    family: Menlo for Powerline
  size: 13.5
  offset:
    y: 5
background_opacity: 0.95
window:
  dimensions:
    columns: 400
    lines: 100
  padding:
    x: 0
    y: 0
cursor:
  style: Block
  unfocusedd_hollow: true
schemes:
  solarized_dark: &solarized_dark
    # Default colors
    primary:
      background: '0x002b36' # base03
      foreground: '0x839496' # base0

    # Cursor colors
    cursor:
      text:   '0x002b36' # base03
      cursor: '0x839496' # base0

    # Normal colors
    normal:
      black:   '0x073642' # base02
      red:     '0xdc322f' # red
      green:   '0x859900' # green
      yellow:  '0xb58900' # yellow
      blue:    '0x268bd2' # blue
      magenta: '0xd33682' # magenta
      cyan:    '0x2aa198' # cyan
      white:   '0xeee8d5' # base2

    # Bright colors
    bright:
      black:   '0x002b36' # base03
      red:     '0xcb4b16' # orange
      green:   '0x586e75' # base01
      yellow:  '0x657b83' # base00
      blue:    '0x839496' # base0
      magenta: '0x6c71c4' # violet
      cyan:    '0x93a1a1' # base1
      white:   '0xfdf6e3' # base3
  monokai_pro: &monokai_pro
    # Default colors
    primary:
      background: "0x2D2A2E"
      foreground: "0xFCFCFA"

    # Normal colors
    normal:
      black: "0x403E41"
      red: "0xFF6188"
      green: "0xA9DC76"
      yellow: "0xFFD866"
      blue: "0xFC9867"
      magenta: "0xAB9DF2"
      cyan: "0x78DCE8"
      white: "0xFCFCFA"

    # Bright colors
    bright:
      black: "0x727072"
      red: "0xFF6188"
      green: "0xA9DC76"
      yellow: "0xFFD866"
      blue: "0xFC9867"
      magenta: "0xAB9DF2"
      cyan: "0x78DCE8"
      white: "0xFCFCFA"
  oceanic_next: &oceanic_next
    # Default colors
    primary:
      background: '0x1b2b34'
      foreground: '0xd8dee9'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x1b2b34'
      cursor: '0xffffff'

    # Normal colors
    normal:
      black:   '0x343d46'
      red:     '0xEC5f67'
      green:   '0x99C794'
      yellow:  '0xFAC863'
      blue:    '0x6699cc'
      magenta: '0xc594c5'
      cyan:    '0x5fb3b3'
      white:   '0xd8dee9'

    # Bright colors
    bright:
      black:   '0x343d46'
      red:     '0xEC5f67'
      green:   '0x99C794'
      yellow:  '0xFAC863'
      blue:    '0x6699cc'
      magenta: '0xc594c5'
      cyan:    '0x5fb3b3'
      white:   '0xd8dee9'
colors: *oceanic_next
