name: CI

on: [push]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy -> Init
        run: |
          make
          make deploy
          make init

  test-centos:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Prepare -> Deploy -> Init
        run: |
          sudo yum install -y make
          make centos_ci
          make deploy
          make init
