name: CI

on: [push]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Make
        run: make
      - name: Deploy
        run: make deploy
      - name: Init
        run: make init

  test-centos:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install
        run: bash install.sh
      - name: Deploy
        run: make deploy
      - name: Init
        run: make init
