name: CI

on: [push]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy -> Init
        run: |
          make
          make deploy
          make init

  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy -> Init
        run: |
          make
          make deploy
          make init
