name: CI

on: [push]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: make
        run: make
      - name: Deploy
        run: make deploy
      - name: Init
        run: make init
